### ISSUE TITLE
Support GPU acceleration?

### ISSUE THREAD

**Issue by KL4805** [HKU-Smart-Mobility-Lab/Transportation_Simulator#30]
Hello authors, 

Thanks for your patience in helping me running your simulator! It now works OK, but an epoch may take ~900s on CPU. I wonder whether your code can support GPU acceleration (or has supported?)

**Comment by Caffretro** [comment]
Yes, it does support GPU acceleration. For training using different simulator methods, you can check the algorithm modules it uses (e.g. A2C.py, sarsa.py, etc.), and configure GPU acceleration environments corresponding to the required machine learning modules.

Since we are not considering upgrading the algorithm's dependencies, the required CUDA and cuDNN versions may differ from yours. You may need to check your CUDA and cuDNN versions, as they may not support the modules our code uses

**Comment by chenhaoling** [comment]
Hi, we find it difficult to configure this version of TensorFlow to support GPU acceleration, you could use Torch to implement the algorithm for dispatching.

**Comment by chenhaoling** [comment]
We have added docker image to support GPU acceleration.
