### ISSUE TITLE
Can you provide the visualization module?

### ISSUE THREAD

**Issue by Fetkou** [HKU-Smart-Mobility-Lab/Transportation_Simulator#36]
Hi, I saw a really cool visualization on your demo video (https://www.youtube.com/watch?v=q25L7lr77ms). 
However, it seems that the only visualization code in this repository is [dynamic_trajectory.py], if I didn't miss something. While this can also visualize the route, it doesn't look so cool or intuitive as the demo video.
So, can you provide the visualization module? Or show me some guide on how to achieve it?

**Comment by chenhaoling** [comment]
Since the code for this repository is supported by another funding, we are not allowed to make the code public. This project uses Baidu's API for visual development. Also, you can refer to another of our repositories where the visualization code is open source (https://github.com/HKU-Smart-Mobility-Lab/map-boardcast).
